### ISSUE TITLE
Support SKI in non-CA certificates

### ISSUE THREAD

**Issue by matthewvalimaki** [hashicorp/terraform-provider-tls#13]
I would like [existing SKI](https://github.com/terraform-providers/terraform-provider-tls/blob/0186f380f6df59fdd3dcefd0b499cd6fa3f74c16/tls/resource_certificate.go#L56) support to be extended to non-CA certificates. For RFC see https://tools.ietf.org/html/rfc5280#section-4.2.1.2. While the RFC says it is mandatory for CA's the way I read it they suggest using SKI with end entity certificates as well.

I came across this with etcd & OpenShift Origin combination where the etcd keys have SKI in the non-CA certificate.

### Terraform Version
Terraform v0.11.3
+ provider.tls v1.0.1

**Comment by matthewvalimaki** [comment]
Here are requirements that OpenShift Origin sets for etcd
```
authorityKeyIdentifier = keyid,issuer:always
basicConstraints       = critical,CA:FALSE
extendedKeyUsage       = clientAuth
keyUsage               = digitalSignature,keyEncipherment
subjectKeyIdentifier   = hash
```
Specifically `subjectKeyIdentifier = hash` says to generate SKI.

**Comment by matthewvalimaki** [comment]
In `resource_certificate.go` we have `createCertificate` in which we have `if d.Get("is_ca_certificate").(bool) {` so I am thinking of adding similar `add_ski` to allow forcing when wanted. Does this make sense? I could work on a PR for this.

**Comment by dawidmalina** [comment]
I'm also looking for more options as @matthewvalimaki. What is blocking me from switching fully to this provider is lack of (mentioned) ```subjectKeyIdentifier: hash``` but also ```authorityKeyIdentifier: keyid,issuer:always```.

@SpencerBrown any updates on this topic?

**Comment by IvanovOleg** [comment]
I have the same issue with kubernetes certs

**Comment by detro** [comment]
Support for `set_subject_key_id` is already in place, since https://github.com/hashicorp/terraform-provider-tls/pull/31
