### ISSUE TITLE
Why does tls_public_key contain private_key_pem

### ISSUE THREAD

**Issue by designermonkey** [hashicorp/terraform-provider-tls#131]
Thi is a security related question not an issue, although the security is an issue in my mind:

Can someone explain why the `private_key_pem` is present inside the output of the `tls_public_key` Data Source?

Surely this is not required as private keys should be hidden from any method of being viewed? It shouldn't be storable in a state file or visible in the output.

I would really like to know the reasoning behind the choice to go this route.

**Comment by akornatskyy** [comment]
Confirmed, still the case in version 3.3.0.

Although security notice exists for [tls_private_key resource](https://registry.terraform.io/providers/hashicorp/tls/latest/docs/resources/private_key), it is actually not stored in `tfstate`.

However, there is no security notice in [tls_public_key data source](https://registry.terraform.io/providers/hashicorp/tls/latest/docs/data-sources/public_key)... in fact private key is in `tfstate` as reported above.

**Comment by detro** [comment]
Hello and thanks for raising this.

Please take a look at our [DESIGN.md](https://github.com/hashicorp/terraform-provider-tls/blob/main/DESIGN.md#patterns) to find guidance and recommendation around how to handle the presence of sensitive values inside the TF state.

As the behaviour is "working as intended" I'm going to close this.
But let me know if you think I'm missing something here.
