### ISSUE TITLE
`tls_certificate` to export fetched certificates in PEM format

### ISSUE THREAD

**Issue by detro** [hashicorp/terraform-provider-tls#192]
### Terraform CLI and Provider Versions

TF >= 0.12
Provider >= 3.3.0

### Use Cases or Problem Statement

This is an aggregation of many _slightly overlapping_ issues and PRs on this subject, and supersedes them:

* #149
* #81
* #82 
* #152

Each PR/issue above covers partially this need, by focusing on a specific scenario.

### Proposal

`tls_certificate` to expose the fetched/loaded certificates as list of PEMs attribute.

This would be a follow up to #189, where a certificate can be provided in PEM format.

### How much impact is this issue causing?

Medium

### Additional Information

Closes #149
Closes #81
Closes #82 
Closes #152

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bflad** [comment]
I may be missing something, but wouldn't 1 and 2 both be resolved with a single conflicting `content` string argument? This is the typical implementation choice of many other providers. Practitioners can use the `file()` configuration language function to locally read a file contents into the string as necessary.

**Comment by iwarapter** [comment]
@bflad thats exactly what I did for #189 whilst ensuring the `url` option continues to work as normal.

**Comment by detro** [comment]
All right then.

@iwarapter I'll shrink the scope of this to only work on exposing the `certs_pem` (or `cert_pems`, not sure yet), and will go on your #189 with comments so we can use that to also close #139.
