### ISSUE TITLE
Support EdDSA/Ed25519 certificates

### ISSUE THREAD

**Issue by jbboehr** [hashicorp/terraform-provider-tls#26]
Would be nice to support EdDSA/Ed25519 certificates. I tried to put together a PR, but without hackey workarounds, it looks like it's going to need some upstream changes in x509: https://github.com/golang/go/issues/25355

**Comment by mattghali** [comment]
Hi! I'd really like to manage keypairs for wireguard in Terraform, but that would require generation of Curve25519 keys. Is this possibly on the roadmap?

thanks!

**Comment by reegnz** [comment]
Go 1.13 is out, and now it supports ED245519 from it's standard library: https://golang.org/doc/go1.13#crypto/ed25519

So there's nothing in the way for terraform-provider-tls to start supporting ed25519 keys.
Anybody willing to pick this up? @jbboehr no hacky workarounds needed anymore. ;)

**Comment by invidian** [comment]
Created PR which adds support for generating ed25519 keys: #59.

**Comment by RobCannon** [comment]
This was merged some time ago, but it was never released.  When can we expect a release with PR#1?

**Comment by jackivanov** [comment]
Any updates on this one?

**Comment by robinkb** [comment]
I am also waiting for this feature to be released.

**Comment by invidian** [comment]
>I am also waiting for this feature to be released.

The PR #59 is up for 6 months now with no feedback. This is just sad. @apparentlymart maybe you could help us somehow with it?

**Comment by PhilippeChepy** [comment]
Any news about implementing the ed25519 algorithm ?

**Comment by c33s** [comment]
@PhilippeChepy have you had a look at https://registry.terraform.io/providers/invidian/tls/latest
i use this provider as workaround for ssh keys. don't know if it also works for certs.

**Comment by kbelosevic** [comment]
Any news on this one?

**Comment by mprenditore** [comment]
Still not supported after 3.5 years?

**Comment by detro** [comment]
Thank you for your time and contribution, we really appreciate it. As part of a bigger effort to add complete support for ED25519 key algorithm, I’m closing this in favor of issue [#150](https://github.com/hashicorp/terraform-provider-tls/issues/150). Please refer to the new issue for what will be included and how work will proceed.
