### ISSUE TITLE
TLS self signed certs don't support update

### ISSUE THREAD

**Issue by NeilW** [hashicorp/terraform-provider-tls#28]
### Terraform Version

neil@xenial-vm:~$ terraform version
Terraform v0.11.7

### Affected Resource(s)
- tls_self_signed_cert

### Terraform Configuration Files
```hcl
resource "tls_private_key" "k8s_etcd_ca" {
  algorithm = "RSA"
}

resource "tls_self_signed_cert" "k8s_etcd_ca" {
  key_algorithm   = "${tls_private_key.k8s_etcd_ca.algorithm}"
  private_key_pem = "${tls_private_key.k8s_etcd_ca.private_key_pem}"

  subject {
    common_name = "cert_name"
    organizational_unit = "etd"
  }

  validity_period_hours = 8160

  allowed_uses = [
    "key_encipherment",
    "digital_signature",
    "cert_signing",
  ]

  is_ca_certificate = true
}
```

### Debug Output
https://gist.github.com/NeilW/9deaba372e62a45b6bf7ede83c7fb37b

### Expected Behavior
Update or replace self-signed key

### Actual Behavior

Error: Error applying plan:

1 error(s) occurred:

* tls_self_signed_cert.k8s_etcd_ca: 1 error(s) occurred:

* tls_self_signed_cert.k8s_etcd_ca: doesn't support update

### Steps to Reproduce
1. `terraform apply`
2. Change organisational unit in TF file from `etd` to `etcd`
3. `terraform apply`

**Comment by kmoe** [comment]
Retested with Terraform v0.12.26, provider.tls v2.1.1, did not reproduce bug. Please reopen if you're still experiencing this issue.
