### ISSUE TITLE
Resource to generate a PKCS #12 archive file out of PKI components

### ISSUE THREAD

**Issue by ebekker** [hashicorp/terraform-provider-tls#29]
It would be useful to support generating a PKCS #12 (PKCS12 or also known as PFX) archive file out of PKI components, including an optional private key, and a chain of one or more certificates.  The current set of TLS resources support generating/exporting to PEM format files, but there are many cases where a PFX archive file is preferred or required such as Windows host environments, Azure provider or Oracle OCI provider.

I recommend supporting this resource in a more general-purpose manner, such that you can give it an optional private key PEM, and one or more certificates (i.e. an array of certificate PEM clobs).  By doing so, the resource would be usable in tandem with other resources of this provider, as well as alternate providers, such as the [third-party ACME cert provider](https://github.com/vancluever/terraform-provider-acme).

An example usage might look like this:
```hcl
## Generate a self-signed cert using a private key stored on disk
resource "tls_self_signed_cert" "example" {
  key_algorithm   = "ECDSA"
  private_key_pem = "${file(\"private_key.pem\")}"

  subject {
    common_name  = "example.com"
    organization = "HCTF Examples, Inc"
  }

  validity_period_hours = 12

  allowed_uses = [
    "key_encipherment",
    "digital_signature",
    "server_auth",
  ]
}

## Produce a PKCS #12 archive of the self-signed cert (private key included)
resource "tls_pkcs12_archive" "example_pfx" {
  private_key_pem = "${file(\"private_key.pem\")}"
  certificate_pem = [
    "${tls_self_signed_cert.example.cert_pem}"
  ]
}

## Save the PKCS #12 archive to an S3 bucket
resource "aws_s3_bucket_object" "example_pfx_s3obj" {
    bucket = "${aws_s3_bucket.example_s3_bucket.id}"
    key    = "pki/example.pfx"

    content = <<EOF
${tls_pkcs12_archive.example_pfx.archive_blob}
EOF
}

```

### Terraform Version
Terraform v0.11.3

### Affected Resource(s)
provider.tls v1.1.0

**Comment by digiwhite1980** [comment]
I guess a password option in some way is also needed...

**Comment by vadimkuznetsov** [comment]
https://github.com/hashicorp/terraform-provider-tls/pull/69

**Comment by rajatrawat99** [comment]
is there any update on this issue?

**Comment by elliotchaim** [comment]
Hi guys any update on this?

**Comment by chilicat** [comment]
I have created a provider that helps to create PKCS12 from PEM files:

https://registry.terraform.io/providers/chilicat/pkcs12/latest/docs/resources/from_pem

**Comment by Poil** [comment]
> I have created a provider that helps to create PKCS12 from PEM files:
> 
> https://registry.terraform.io/providers/chilicat/pkcs12/latest/docs/resources/from_pem

It will be nice to also have a datasource to read a PFX and allow to get his private key and cert
Regards

**Comment by detro** [comment]
Superseded by #205.
