### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by dolevf** [hashicorp/terraform-provider-tls#432]
### Terraform CLI and Provider Versions

N/A

### Use Cases or Problem Statement

Hi there,

There are some CVEs that have been fixed over the last couple of months, It's been sometime since a new release was published and we would love to get a version update so patching is possible.

Thank you!

### Proposal

N/A

### How much impact is this issue causing?

High

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by austinvalle** [comment]
Hi @dolevf 👋🏻,

We're working through releases on all of the utility providers and just released [`v4.0.5`](https://github.com/hashicorp/terraform-provider-tls/releases/tag/v4.0.5) of the `tls` provider with updated dependencies built with Go 1.20 (no functional changes).

It may take an hour or so to update in the registry cache. Thanks!
