### ISSUE TITLE
Add support for subject alternative name URIs

### ISSUE THREAD

**Issue by subnova** [hashicorp/terraform-provider-tls#49]
Provider should support setting URIs within the subject alternative name in the same way as it supports setting DNS names and IP addresses.

### Affected Resource(s)
Please list the resources as a list, for example:
- tls_cert_request
- tls_self_signed_cert

Propose adding a `uris` attribute to the resources that takes a list of strings that results in the URI being parsed and stored in the X509 CertificateRequest/Certificate URIs field.

**Comment by ohookins** [comment]
Seems like this is supported, unless I misunderstand something?
https://github.com/hashicorp/terraform-provider-tls/blob/main/internal/provider/resource_cert_request.go#L121-L128

**Comment by subnova** [comment]
Yes fixed in https://github.com/hashicorp/terraform-provider-tls/pull/50
