### ISSUE TITLE
Creating a CA certificate should set Authority Key Identifier attribute

### ISSUE THREAD

**Issue by seboudry** [hashicorp/terraform-provider-tls#56]
Hi !

By reviewing the code, I found a little mistake when creating a a CA self-signed certificate.
Resource: `tls_self_signed_cert`

https://github.com/terraform-providers/terraform-provider-tls/blob/cb21e556b00b4d8d5fc4073b941ddd5a9c2c0395/tls/resource_certificate.go#L169
Should `AuthorityKeyId` be set instead of `SubjectKeyId` when using `is_ca_certificate`?

**Comment by binlab** [comment]
The same issue I saw, when we creating a CA is `X509v3 Authority Key Identifier` extension missed. Could you comment on this behavior?

**Comment by Sebor** [comment]
I have the same issue. Moreover I suspect that it causes problem for windows OS (because I get `NET::ERR_CERT_AUTHORITY_INVALID` even after importing root CA)

**Comment by karelorigin** [comment]
https://github.com/hashicorp/terraform-provider-tls/pull/66 is supposed to patch this issue but hasn't been active in a while. Any updates from HashiCorp would be great.
