### ISSUE TITLE
subject block required, all fields optional, but cannot pass empty block

### ISSUE THREAD

**Issue by StephenWithPH** [hashicorp/terraform-provider-tls#61]
### Terraform Version
```
Terraform v0.12.10
+ provider.tls v2.1.1
```

### Affected Resource(s)
Please list the resources as a list, for example:
- `tls_cert_request`
- `tls_self_signed_cert`

### Terraform Configuration Files
- fails:
  ```hcl
  resource "tls_private_key" "this" {
    algorithm = "RSA"
  }
  resource "tls_self_signed_cert" "this" {
    early_renewal_hours   = 720
    key_algorithm         = "RSA"
    private_key_pem       = tls_private_key.this.private_key_pem
    validity_period_hours = 2160
  }
  ```
- fails:
  ```hcl
  resource "tls_private_key" "this" {
    algorithm = "RSA"
  }
  resource "tls_self_signed_cert" "this" {
    early_renewal_hours   = 720
    key_algorithm         = "RSA"
    private_key_pem       = tls_private_key.this.private_key_pem
    validity_period_hours = 2160
    subject {}
  }
  ```
- fails:
  ```hcl
  resource "tls_private_key" "this" {
    algorithm = "RSA"
  }
  resource "tls_self_signed_cert" "this" {
    early_renewal_hours   = 720
    key_algorithm         = "RSA"
    private_key_pem       = tls_private_key.this.private_key_pem
    validity_period_hours = 2160
    subject {
      common_name = "" # <--- note the empty string
    }
  }
  ```
- succeeds:
  ```hcl
  resource "tls_private_key" "this" {
    algorithm = "RSA"
  }
  resource "tls_self_signed_cert" "this" {
    early_renewal_hours   = 720
    key_algorithm         = "RSA"
    private_key_pem       = tls_private_key.this.private_key_pem
    validity_period_hours = 2160
    subject {
      common_name = " " # <--- note the space... this is the kludge to get it to work
    }
  }
  ```

### Expected Behavior
Terraform generates the `tls_self_signed_cert` resource with no subject field on the certificate, and Terraform demands no `subject` block at all.

### Actual Behavior
Fails with this error when no subject block:
https://github.com/terraform-providers/terraform-provider-tls/blob/afd9e9546f57b662e375ef4146c0209e1b75c6f6/tls/resource_cert_request.go#L94

Fails with this error when an empty subject block:
https://github.com/terraform-providers/terraform-provider-tls/blob/afd9e9546f57b662e375ef4146c0209e1b75c6f6/tls/resource_cert_request.go#L98

Fails with this (same) error when subject block has single field explicitly set to an empty string `common_name =  ""`:
https://github.com/terraform-providers/terraform-provider-tls/blob/afd9e9546f57b662e375ef4146c0209e1b75c6f6/tls/resource_cert_request.go#L98

### Steps to Reproduce
1. `terraform apply` with the first set of configs (labelled "fails") above.

### Important Factoids
I believe this was introduced in https://github.com/terraform-providers/terraform-provider-tls/pull/7. That issue is addressing a (valid) user behavior of providing no subject at all (https://github.com/terraform-providers/terraform-provider-tls/issues/1) which had been causing a panic.

I think this all stems from type coercion:
https://github.com/terraform-providers/terraform-provider-tls/blob/afd9e9546f57b662e375ef4146c0209e1b75c6f6/tls/resource_cert_request.go#L96

... which is only necessary because `subject` is (unnecessarily) marked required:
https://github.com/terraform-providers/terraform-provider-tls/blob/afd9e9546f57b662e375ef4146c0209e1b75c6f6/tls/resource_cert_request.go#L71-L76

Of note, the code which parses the subject block's fields treats all of them as optional:
https://github.com/terraform-providers/terraform-provider-tls/blob/afd9e9546f57b662e375ef4146c0209e1b75c6f6/tls/provider.go#L35-L70

### References
- https://tools.ietf.org/html/rfc5280#section-4.1.2.6 implies that an empty subject field is valid:
  >Where it is non-empty, the subject field MUST contain an X.500
   distinguished name (DN)

**Comment by joshua9519** [comment]
I have a use case for this functionality and so would like to see this get fixed. 
@StephenWithPH are you suggesting just removing the requirement of the subject block?

**Comment by StephenWithPH** [comment]
> are you suggesting just removing the requirement of the subject block?

Yes. To me, the ideal behavior is that Terraform generates the tls_self_signed_cert resource with no subject field on the certificate, and Terraform demands no subject block at all.

**Comment by nathanhleung** [comment]
I'm experiencing this too -- my `common_name` used to be the domain associated with my cert, but I now want to use the cert for multiple domains so I want to get rid of the subject.

**Comment by nathanhleung** [comment]
> I'm experiencing this too -- my `common_name` used to be the domain associated with my cert, but I now want to use the cert for multiple domains so I want to get rid of the subject.

Following up on this -- I was using the `tls_cert_request` resource, and setting extra domains in the `dns_names` list puts them in the cert's SAN. I just kept the initial domain in the subject as before.
