### ISSUE TITLE
Go module versioning needs fixed

### ISSUE THREAD

**Issue by lazzurs** [hashicorp/terraform-provider-tls#67]
### Terraform Version

Latest

### Affected Resource(s)

N/A

### Terraform Configuration Files

N/A

### Expected Behavior

As described here once the version of a go module hits greater than v1 the path needs changed.

https://github.com/golang/go/wiki/Modules#releasing-modules-v2-or-higher

### Actual Behavior

The path of this provider has not been changed so the latest version can not be pulled by other projects/providers.

### Important Factoids

This provider is being included in acme provider and it cannot move to the Terraform Plugin SDK until this fix has been made to this provider.

### References

I have started a fix for this in PR #64

**Comment by kmoe** [comment]
Importing providers as Go modules is not supported (please see [best practice documentation](https://www.terraform.io/docs/extend/best-practices/depending-on-providers.html#do-not-import-providers-as-go-modules)), so this is not necessary.
