### ISSUE TITLE
unsupported attribute "ready_for_renewal"

### ISSUE THREAD

**Issue by dossy** [hashicorp/terraform-provider-tls#72]
### Terraform Version

```
$ terraform -v
Terraform v0.12.24
+ provider.azurerm v2.3.0
+ provider.local v1.4.0
+ provider.null v2.1.2
+ provider.tls v2.0.1
```

### Affected Resource(s)

* `tls_cert_request`
* `tls_locally_signed_cert`
* https://github.com/hashicorp/terraform-provider-tls/blob/master/tls/resource_certificate.go

### Terraform Configuration Files

[ need to create a minimal reproducible configuration ]

### Debug Output

```
2020/04/02 16:00:23 [DEBUG] ReferenceTransformer: "tls_cert_request.int_ca" references: []
2020/04/02 16:00:23 [DEBUG] ReferenceTransformer: "module.REDACTED.tls_cert_request.this" references: []
2020/04/02 16:00:23 [DEBUG] ReferenceTransformer: "tls_self_signed_cert.root_ca" references: []
2020/04/02 16:00:23 [ERROR] <root>: eval: *terraform.EvalReadState, err: unsupported attribute "uris"
2020/04/02 16:00:23 [ERROR] <root>: eval: *terraform.EvalSequence, err: unsupported attribute "uris"
2020/04/02 16:00:23 [ERROR] <root>: eval: *terraform.EvalReadState, err: unsupported attribute "ready_for_renewal"
2020/04/02 16:00:23 [ERROR] <root>: eval: *terraform.EvalSequence, err: unsupported attribute "ready_for_renewal"
module.REDACTED.tls_cert_request.this: Refreshing state... [id=dced9383cfe02c4c488ad3464e70fc5eebce3838]

Error: unsupported attribute "ready_for_renewal"



Error: unsupported attribute "uris"
```

### Panic Output

N/A

### Expected Behavior

The SSL certificate should have been generated.

### Actual Behavior

The following errors were returned:

```
Error: unsupported attribute "ready_for_renewal"
Error: unsupported attribute "uris"
```

### Steps to Reproduce

Please list the steps required to reproduce the issue, for example:

1. `terraform apply -target=module.REDACTED.tls_locally_signed_cert.this`

### Important Factoids

Terraform state stored remotely in Azure Storage.

### References

N/A

**Comment by kmoe** [comment]
Thanks for the update. I can't confirm the fix without a minimal reproduction case, but please reopen this issue if you experience the same problem again.
