### ISSUE TITLE
Consistent ID across multiple planning

### ISSUE THREAD

**Issue by caruccio** [hashicorp/terraform-provider-tls#79]
### Terraform Version

```
terraform -v
Terraform v0.13.2
+ provider registry.terraform.io/hashicorp/tls v2.2.0
```
### Affected Resource(s)
Please list the resources as a list, for example:
- tls_certificate

### Terraform Configuration Files
```hcl
data "tls_certificate" "oidc_idp" {
  url = "https://oidc.eks.sa-east-1.amazonaws.com/id/<REDACTED>"
}
```

### Expected Behavior
Consistent `id` across consecutive plans.

### Actual Behavior
Resource `id` changes every plan even if certificates are the same.

```
...
      ~ id           = "2020-09-14 19:34:14.498463939 +0000 UTC" -> "2020-09-14 19:34:14.722109742 +0000 UTC"
...
```

### Steps to Reproduce
1. `terraform plan .`
2. `terraform apply .`
3. `terraform plan .`

### Important Factoids
Obviously, this is the behavior given by [this line](https://github.com/hashicorp/terraform-provider-tls/blob/f1b91f494149cc797fd710691c66fcf8a73c9469/tls/data_source_tls_certificate.go#L109).
Is this intentional? Could it be something stable, like the certificate's serial number or sha1 fingerprint?

**Comment by Fuuzetsu** [comment]
The problem is made worse by the fact that the usual `lifecycle { ignore_changes = [id] }` approach one might want to take does not work:

```
Error: Unsupported lifecycle block

  on ../modules/main_vpc/eks.tf line 338, in data "tls_certificate" "oidc":
 338:   lifecycle {

Data resources do not have lifecycle settings, so a lifecycle block is not
allowed.
```

**Comment by xenji** [comment]
So, would the sha1_fingerprint a good ID? It would have the positive side-effect, that it would make a change in this property very visible.

**Comment by amirba-mistral** [comment]
Any new info, does somebody found solutions to this problem?

**Comment by Z3R6** [comment]
Any updates?

**Comment by amirba-mistral** [comment]
> Any updates?

I solve this problem with an update of Terraform to version "0.14.2".

**Comment by caruccio** [comment]
@amirba-mistral AFAIU this is the line that sets this id: https://github.com/hashicorp/terraform-provider-tls/blob/v3.0.0/internal/provider/data_source_tls_certificate.go#L109

What is the provider version you are using?

**Comment by Z3R6** [comment]
> > Any updates?
> 
> I solve this problem with an update of Terraform to version "0.14.2".

I also solved this problem with update Terraform to version "0.14.2".
Thanks!
